"""removed unique constraints

Revision ID: 24c57420f568
Revises: 88b74e50e05d
Create Date: 2024-11-19 18:00:35.321342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24c57420f568'
down_revision = '88b74e50e05d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_restaurant_cart', 'carts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_restaurant_cart', 'carts', ['user_id', 'restaurant_id'])
    # ### end Alembic commands ###
