"""removed cart item

Revision ID: 88b74e50e05d
Revises: 8178a61c68cb
Create Date: 2024-11-19 17:49:33.272377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88b74e50e05d'
down_revision = '8178a61c68cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_items')
    op.add_column('carts', sa.Column('menu_item_id', sa.Integer(), nullable=False))
    op.add_column('carts', sa.Column('quantity', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'carts', 'menu_items', ['menu_item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_column('carts', 'quantity')
    op.drop_column('carts', 'menu_item_id')
    op.create_table('cart_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_positive_quantity'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name='cart_items_cart_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], name='cart_items_menu_item_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cart_items_pkey')
    )
    # ### end Alembic commands ###
